# Generated by Django 5.2.17 on 2026-08-29 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='family_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='guests.guest', verbose_name='Chefe da família'),
        ),
        migrations.AddField(
            model_name='guest',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='guest',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='Slug da família'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='response',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('declined', 'Negado')], default='pending', max_length=20, verbose_name='Resposta'),
        ),
    ]
